name: A Certain Scientific Railgun T
on:
  push:
    branches:
      - master
      
env:
  name: "Firefox Setup 79.0"
  comment: "Firefox Setup 79.0"
  url: https://drive.google.com/drive/folders/1Hvzxc2wkrzsL_Myh3SgmcHvjQiVzKEOg?usp=sharing
  file_name: "Railgun T"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
